/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as HomegigsGigGigIdRouteImport } from './routes/home/(gigs)/gig.$gigId'

const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomegigsGigGigIdRoute = HomegigsGigGigIdRouteImport.update({
  id: '/home/(gigs)/gig/$gigId',
  path: '/home/gig/$gigId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/home': typeof HomeIndexRoute
  '/home/gig/$gigId': typeof HomegigsGigGigIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/home': typeof HomeIndexRoute
  '/home/gig/$gigId': typeof HomegigsGigGigIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/home/': typeof HomeIndexRoute
  '/home/(gigs)/gig/$gigId': typeof HomegigsGigGigIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/signup' | '/home' | '/home/gig/$gigId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/signup' | '/home' | '/home/gig/$gigId'
  id:
    | '__root__'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/home/'
    | '/home/(gigs)/gig/$gigId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HomegigsGigGigIdRoute: typeof HomegigsGigGigIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(gigs)/gig/$gigId': {
      id: '/home/(gigs)/gig/$gigId'
      path: '/home/gig/$gigId'
      fullPath: '/home/gig/$gigId'
      preLoaderRoute: typeof HomegigsGigGigIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomegigsGigGigIdRoute: HomegigsGigGigIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
